#!/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh






#   _____ ____  _   _ ______ _____ _____
#  / ____/ __ \| \ | |  ____|_   _/ ____|
# | |   | |  | |  \| | |__    | || |  __
# | |   | |  | | . ` |  __|   | || | |_ |
# | |___| |__| | |\  | |     _| || |__| |
#  \_____\____/|_| \_|_|    |_____\_____|

#bspc config border_radius       8
bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          20
bspc config bottom_padding       2
bspc config left_padding         2
bspc config right_padding        2
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true



#  _____ ____  _      ____  _____   _____
# / ____/ __ \| |    / __ \|  __ \ / ____|
# | |   | |  | | |   | |  | | |__) | (___
# | |   | |  | | |   | |  | |  _  / \___ \
# | |___| |__| | |___| |__| | | \ \ ____) |
#  \_____\____/|______\____/|_|  \_\_____/

bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#a61e9c"
bspc config focused_border_color	"#a61e9c"
bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"




#  __  __  ____  _   _ _____ _______ ____  _____   _____
# |  \/  |/ __ \| \ | |_   _|__   __/ __ \|  __ \ / ____|
# | \  / | |  | |  \| | | |    | | | |  | | |__) | (___
# | |\/| | |  | | . ` | | |    | | | |  | |  _  / \___ \
# | |  | | |__| | |\  |_| |_   | | | |__| | | \ \ ____) |
# |_|  |_|\____/|_| \_|_____|  |_|  \____/|_|  \_\_____/


#Single monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#Dual monitor
#find out names with arandr or xrandr
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 1 2 3 4
#bspc monitor DP3 -d  5 6 7 8 9
#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI1 -d 1 2 3 4 5
#bspc monitor HDMI2 -d 6 7 8 9 10






# ______ _    _ _      _       _____  _____ _____  ______ ______ _   _
# |  ____| |  | | |    | |     / ____|/ ____|  __ \|  ____|  ____| \ | |
# | |__  | |  | | |    | |    | (___ | |    | |__) | |__  | |__  |  \| |
# |  __| | |  | | |    | |     \___ \| |    |  _  /|  __| |  __| | . ` |
# | |    | |__| | |____| |____ ____) | |____| | \ \| |____| |____| |\  |
# |_|     \____/|______|______|_____/ \_____|_|  \_\______|______|_| \_|


bspc rule -a inkscape state=fullscreen
#bspc rule -a Spotify state=fullscreen
bspc rule -a Vlc state=fullscreen
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen
#bspc rule -a Gimp state=fullscreen







#  ______ _      ____       _______ _____ _   _  _____
# |  ____| |    / __ \   /\|__   __|_   _| \ | |/ ____|
# | |__  | |   | |  | | /  \  | |    | | |  \| | |  __
# |  __| | |   | |  | |/ /\ \ | |    | | | . ` | | |_ |
# | |    | |___| |__| / ____ \| |   _| |_| |\  | |__| |
# |_|    |______\____/_/    \_\_|  |_____|_| \_|\_____|

bspc rule -a Arandr state=floating
bspc rule -a feh state=floating
bspc rule -a Galculator state=floating
bspc rule -a Oblogout state=floating
bspc rule -a Xfce4-terminal state=floating



#  _______ _____ _      ______ _____
# |__   __|_   _| |    |  ____|  __ \
#    | |    | | | |    | |__  | |  | |
#    | |    | | | |    |  __| | |  | |
#    | |   _| |_| |____| |____| |__| |
#    |_|  |_____|______|______|_____/

bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled
bspc rule -a emacs state=tiled



# __          ______  _____  _  __ _____ _____        _____ ______
# \ \        / / __ \|  __ \| |/ // ____|  __ \ /\   / ____|  ____|
#  \ \  /\  / / |  | | |__) | ' /| (___ | |__) /  \ | |    | |__
#   \ \/  \/ /| |  | |  _  /|  <  \___ \|  ___/ /\ \| |    |  __|
#    \  /\  / | |__| | | \ \| . \ ____) | |  / ____ \ |____| |____
#   __\/_ \/___\____/|_|__\_\_|\_\_____/|_|_/_/_ __\_\_____|______|
#  / ____|  __ \|  ____/ ____|_   _|  ____|_   _|  ____|  __ \
# | (___ | |__) | |__ | |      | | | |__    | | | |__  | |  | |
#  \___ \|  ___/|  __|| |      | | |  __|   | | |  __| | |  | |
#  ____) | |    | |___| |____ _| |_| |     _| |_| |____| |__| |
# |_____/|_|    |______\_____|_____|_|    |_____|______|_____/

bspc rule -a Chromium desktop='^3'  follow=on
#bspc rule -a Subl3 desktop='^2' follow=on
bspc rule -a Steam desktop='^9'
bspc rule -a discord desktop='^8' follow=on
#bspc rule -a Spotify desktop='^10' follow=on

